name: gov_client_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get_it: 8.0.2
  sentry_flutter: ^8.9.0
  gov_portal_core_u_i_presentation:
    git:
      url: git@github.com:ff-vivek/gov_portal_core_u_i_presentation.git

  gov_portal_core_u_i_input:
    git:
      url: git@github.com:ff-vivek/gov_portal_core_u_i_input.git

  gov_portal_core_u_i_nav:
    git:
      url: git@github.com:ff-vivek/gov_portal_core_u_i_nav.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true