name: gov_client_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get_it: 8.0.2
  sentry_flutter: ^8.9.0
  gov_portal_core_u_i_presentation:
    git:
      url: git@github.com:ff-vivek/gov_portal_core_u_i_presentation.git

  gov_portal_core_u_i_input:
    git:
      url: git@github.com:ff-vivek/gov_portal_core_u_i_input.git

  gov_portal_core_u_i_nav:
    git:
      url: git@github.com:ff-vivek/gov_portal_core_u_i_nav.git

dev_dependencies:
  test: any
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  sentry_dart_plugin: ^2.0.0

flutter:
  uses-material-design: true

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  upload_sources: true
  project: "gov-portal-poc"
  org: "flutterflow-7d"
  auth_token: "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"
  wait_for_processing: false
  web_build_path: build/web
  commits: auto
  ignore_missing: true
